### ISSUE TITLE
<br> in custom tooltips?

### ISSUE THREAD

**Issue by matthias-range-ais** [RonnyWeiss/APEX-Material-BI-Dashboard#2]
Hi Ronny,

why there is an additional `<br>` after a custom tooltip? 
I think it looks a bit messy.

Line 2916:
`if (seriesData[key][index] && util.isDefinedAndNotNull(seriesData[key][index].tooltip)) {
   var ttS = escapeOrSanitizeHTML(seriesData[key][index].tooltip, pDefaultConfig, pIsSafeItem, pRequireHTMLEscape);
   div.append(ttS);
   div.append("<br>");
 }`

Is it possible to remove the tag, or does it have a function?

**Comment by RonnyWeiss** [comment]
Hi Matthias,

Thank you for reporting this issue. I will fix this issue in version 1.0.0.25
