### ISSUE TITLE
inverted treshhold rule for the single gauge chart

### ISSUE THREAD

**Issue by matthias-range-ais** [RonnyWeiss/APEX-Material-BI-Dashboard#3]
Hi Ronny,

i think the lable threshold logic for gauge charts sholud be inverted from
Line 2975
`threshold: (gaugeType === "single") ? 0.05 : null`
to
`threshold: (gaugeType === "single") ? null : 0.05`

Otherwise, the single display has the effect that the label suddenly disappears in the middle of the chart at values < 5%.
Perhaps it would also be a good idea to be able to optionally specify the attributes via the config.

**Comment by RonnyWeiss** [comment]
Hi Matthias 

in version 1.0.0.25 I will add option to set the threshold for the pie, donut and gauge charts
