### ISSUE TITLE
Short notes with controls like CKEditor possible?

### ISSUE THREAD

**Issue by McRange** [RonnyWeiss/APEX-Material-BI-Dashboard#5]
Hi Ronny,

A customer would like to have some additional functions for editing his notes, which he already knows from the CKEditor, e.g. 

* Colorize text or background (highlite)
* Normal style
* Undo function
* checkbox (that would be awesome)

Perhaps a function would be possible, where you can define the actions yourself.

Many greetings!
Matthias

**Comment by RonnyWeiss** [comment]
Development Done. Will be included in next Release
