### ISSUE TITLE
Support stickyHeaderDates for Calendar config

### ISSUE THREAD

**Issue by stefan-werner-ais** [RonnyWeiss/APEX-Material-BI-Dashboard#6]
Hi Ronny,

would it be possible to integrate "stickyHeaderDates " as an addtional config parameter for the FullCalendar?

best regards,
Stefan

**Comment by RonnyWeiss** [comment]
Development Done. Will be included in next Release.

**Comment by stefan-werner-ais** [comment]
Thanks very much!
